from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from config import DOCS_FOLDER


def clean_filename(filename: str) -> str:
    allowed = (
        "abcdefghijklmnopqrstuvwxyz"
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "0123456789-_"
    )

    return "".join(
        char if char in allowed else "_"
        for char in filename
    )


def create_docx(
    document_text: str,
    document_type: str
) -> str:

    document = Document()

    # Default font
    styles = document.styles
    styles["Normal"].font.name = "Arial"
    styles["Normal"].font.size = Pt(11)

    # Title
    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run(document_type.upper())
    run.bold = True
    run.font.size = Pt(16)

    document.add_paragraph()

    # Add document content
    paragraphs = document_text.split("\n")

    for paragraph_text in paragraphs:

        paragraph_text = paragraph_text.strip()

        if not paragraph_text:
            document.add_paragraph()
            continue

        paragraph = document.add_paragraph()

        # Detect simple headings
        if (
            paragraph_text.isupper()
            or paragraph_text.startswith("#")
            or paragraph_text.lower().startswith("article ")
            or paragraph_text.lower().startswith("section ")
        ):
            run = paragraph.add_run(
                paragraph_text.replace("#", "").strip()
            )
            run.bold = True
        else:
            paragraph.add_run(paragraph_text)

    # Footer
    footer = document.sections[0].footer
    footer_paragraph = footer.paragraphs[0]
    footer_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_paragraph.add_run(
        "Generated by LegalEase - AI Powered Documentation Generator"
    ).font.size = Pt(8)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    safe_type = clean_filename(document_type)

    filename = f"{safe_type}_{timestamp}.docx"

    output_folder = Path(DOCS_FOLDER)
    output_folder.mkdir(parents=True, exist_ok=True)

    output_path = output_folder / filename

    document.save(output_path)

    return str(output_path)